# Generated by Django 5.0.6 on 2024-05-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
